sudo: required
dist: trusty

env:
  matrix:
  global:
    - TILEDB_BUILD_DIR=$TRAVIS_BUILD_DIR/build
    - secure: FY0kC/WNeghc7tffE/Lksir33wAGBRAyQ3Zo2QDb8KOaspT9lUnraW+vLgGTqbV1xJLYWszYv4tKxbiNLV78pfJ886FsZUv5FDiz93EmM7zIAM8moXqjFhwkq9PBKDfGTbkIEt3Ris5himIegSj5Jnpvxw+BhngDy9dFylLox55fsDc88ZjDBTMv1NRJQc2hWmi7unfkzz0Bmq4Ao9OvBqHDqwTt9ZAfmZQEHlrmojuPX8uENp9jQ+8Pgrl/Lv9HjFnHeQAhXHufWztCzUcw84ywnf14VF9ifJhb7nmMEa1itZTVW7QLOQhRZrKKv1ecgE2qt+i3hqN5W+8xR8sc3iKWqyrB3j2uZMrR4njtfoBYREXATS02+nzJQblSZMJh+clm6R4X30Z2F5SJuVW6k2Gr3Zme7B3HJZJWzscwV35aSbUQeCFro6LDrGPhLcuVYLnIVxwol7u72qh61hOOTfX4j38gWxTM/3uyNpQGfUjtk+CscdZvuYy2+ayt8BWilf4hDRpypJ9tQaNxOKLBB4Agv4Tvm5mwTly1OL3uE7MMzap3LD2li6MBFmwzjkY4YKnM9pji0gOs131RNBh1CnbcpzU5HdnLjwbA79Mhr+L1vxvHPcvuY2vd5YNygWHg2f7wYpIFxpkWWA80AwHEuJIsKK7GrVvHlDh7g3onmm4=

matrix:
  include:
    - name: "Basic build"
      os: linux
      env: INSTALL_TYPE=basic

    - name: "Basic build - all codec"
      os: linux
      env: INSTALL_TYPE=basic INSTALL_CODEC=true

    - name: "HDFS support"
      os: linux
      env: INSTALL_TYPE=hdfs

    - name: "GCS support"
      os: linux
      env: INSTALL_TYPE=gcs

    - name: "Basic build - OSX"
      os: osx
      env: INSTALL_TYPE=basic ENABLE_ZSTD=0 ENABLE_BLOSC=0 ENABLE_LZ4=0

before_install:
    - if [[ $INSTALL_TYPE == gcs ]]; then
        pushd $TRAVIS_BUILD_DIR/.travis/resources/gcs;
        echo "GS_BUCKET=" $GS_BUCKET;
        openssl aes-256-cbc -K $encrypted_e618d734a0d0_key -iv $encrypted_e618d734a0d0_iv -in GCS.json.enc -out ~/GCS.json -d;
        echo "Listing gcs";
        ls -l;
        popd;
      fi

install:
    - if [[ $TRAVIS_OS_NAME == linux ]]; then
        sudo apt-get -y install cmake lcov mpich;
        sudo apt-get -y install zlib1g-dev libssl-dev uuid-dev;
        source $TRAVIS_BUILD_DIR/.travis/scripts/install_supported_codec.sh;
        if [[ $INSTALL_TYPE != basic ]]; then
          source $TRAVIS_BUILD_DIR/.travis/scripts/install_hadoop.sh;
          echo "HADOOP CLASSPATH=" $CLASSPATH;
        fi
      elif [[ $TRAVIS_OS_NAME == osx ]]; then
        brew install cmake lcov mpich ;
        brew install openssl, ossp-uuid;
      else
        echo "Platform $TRAVIS_OS not yet supported";
        exit 1;
      fi

    # Install lcov to coveralls conversion + upload tool
    - gem install coveralls-lcov

    # Build TileDB
    - rm -rf $TILEDB_BUILD_DIR
    - mkdir -p $TILEDB_BUILD_DIR
    - cd $TILEDB_BUILD_DIR

    - cmake -DCMAKE_BUILD_TYPE=Coverage -DENABLE_ZSTD=$ENABLE_ZSTD -DENABLE_BLOSC=$ENABLE_BLOSC -DENABLE_LZ4=$ENABLE_LZ4 ..
    - make -j 4

before_script:
    - lcov --directory $TILEDB_BUILD_DIR --zerocounters

script:
    - if [[ $INSTALL_TYPE != basic ]]; then
        $TRAVIS_BUILD_DIR/.travis/scripts/run_dfs_tests.sh;
      else
        make tests -j 4;
      fi

after_success:
    - cd $TILEDB_BUILD_DIR
    - find test -name *.gcda -type f -delete
    - find examples -name *.gcda -type f -delete
    - find deps -name *.gcda -type f -delete
    - lcov --directory core --capture --output-file coverage.info
    - lcov --remove coverage.info '/opt*' '*/usr/*' -o coverage.info
    - lcov --list coverage.info
    # Uploading report to CodeCov
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
